FROM klabberlin/node:6.1.0
MAINTAINER Max Kimambo <max.kimambo@klab-berlin.com>
ENV NODE_ENV=development
ENV PORT=3000
WORKDIR /var/www
COPY . /var/www
#use ADD/COPY if you want to build image to ship
#exposes a port from the container to which you can later bind to
EXPOSE $PORT
#this is the command that will be executed once the container has started
ENTRYPOINT ["node", "www/bin"]
